package com.kaltura.playkit.plugins.ads.ima;

import com.kaltura.playkit.PKEvent;
import com.kaltura.playkit.Player;
import com.kaltura.playkit.PlayerEvent;

/**
 * Created by gilad.nadav on 21/11/2016.
 */

public enum IMAEvents implements PKEvent {
    IMA_STARTED,
    IMA_PAUSED,
    IMA_RESUMED,
    IMA_COMPLETED,
    IMA_FIRST_QUARTILE,
    IMA_MIDPOINT,
    IMA_THIRD_QUARTILE,
    IMA_SKIPPED,
    IMA_CLICKED,
    IMA_TAPPED,
    IMA_ICON_TAPPED,
    IMA_AD_BREAK_READY,
    IMA_AD_PROGRESS,
    IMA_AD_BREAK_STARTED,
    IMA_AD_BREAK_ENDED,
    IMA_CUEPOINTS_CHANGED,
    IMA_LOADED,
    IMA_CONTENT_PAUSE_REQUESTED,
    IMA_CONTENT_RESUME_REQUESTED,
    IMA_ALL_ADS_COMPLETED,

    IMA_INTERNAL_ERROR,
    IMA_VAST_MALFORMED_RESPONSE,
    IMA_UNKNOWN_AD_RESPONSE,
    IMA_VAST_LOAD_TIMEOUT,
    IMA_VAST_TOO_MANY_REDIRECTS,
    IMA_VIDEO_PLAY_ERROR,
    IMA_VAST_MEDIA_LOAD_TIMEOUT,
    IMA_VAST_LINEAR_ASSET_MISMATCH,
    IMA_OVERLAY_AD_PLAYING_FAILED,
    IMA_OVERLAY_AD_LOADING_FAILED,
    IMA_VAST_NONLINEAR_ASSET_MISMATCH,
    IMA_COMPANION_AD_LOADING_FAILED,
    IMA_UNKNOWN_ERROR,
    IMA_VAST_EMPTY_RESPONSE,
    IMA_FAILED_TO_REQUEST_ADS,
    IMA_VAST_ASSET_NOT_FOUND,
    IMA_ADS_REQUEST_NETWORK_ERROR,
    IMA_INVALID_ARGUMENTS,
    IMA_PLAYLIST_NO_CONTENT_TRACKING;

    @Override
    public Object eventId() {
        return this;
    }

    public interface Listener {
        void onPlayerEvent(Player player, PlayerEvent event);
    }
}
