name: build CI

on:
  push:
    branches: [ "dev", "master", "main" ]
  pull_request:
    branches: [ "dev", "master", "main" ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle-build:
    environment: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo and clone to CI workspace
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Gradle Build...
        run: ./gradlew build
